version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://db/mern-trpc
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: db
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    logging:
      driver: none